### ISSUE TITLE
bump up flask version

### ISSUE THREAD

**Issue by Fnalsk** [andrewrosss/flask-firebase-admin#8]
Can the flask version be bumped up to the latest (2.0.1)?

**Comment by andrewrosss** [comment]
Hey @Fnalsk, seems like a good idea. It looks like this package should be compatible with flask 2.x.

I just cut a new release with the updated dependencies. Can you give version `0.2.4` a try?

Of course, feel free to either re-open this issue or open a new one if there are any problems.

**Comment by Fnalsk** [comment]
yup, seems to work. Thanks!
